### PR TITLE
feature: support 'Agua Requerido' tag

### PR DESCRIPTION
**Pull request by okdistribute**
Show information for communities that will have water installations coming in 2018

TODO:
- [x] add new icons: `comunidad-agua-requerido-dot.svg` and `comunidad-agua-requerido.svg`
- [x] add a new icon for water required on the sidebar
- [x] add to legend

- [ ] replace `comunidad-agua-requerido.svg` with a new one that is a house. right now it's a dot.
- [ ] upload the new icons to the mapbox style

### CODE REVIEW

**Comment by okdistribute** [comment]
@gmaclennan this is ready minus those two small icon TODOs. Can you upload the appropriate icons to mapbox style?

**Comment by gmaclennan** [comment]
@karissa both the icons I see in the repo are the same (`comunidad-agua-requerido.svg` and `comunidad-agua-requerido-dot.svg`). I made some fixes to them because Mapbox Studio did not like the SVG that Illustrator exported (I used Inkscape) and I uploaded them so they are available with the icon names `comunidad-agua-requerido` and `comunidad-agua-requerido-dot` and it looks like it works.

On a broader note, I believe this change is specifically for the water campaign map, not for the general map that also shows solar. I think with solar too it adds too much into to the map.

Also, I think the `Agua Requerido` field is useful for populating the sidebar, but I think for the map icons we should use the "Estatus" field, which has "Planned", "In progress" and "complete" options.

**Comment by okdistribute** [comment]
@gmaclennan yeah I agree it should only be on the water map.

Curious if you have any insight on the colors for the dots on the map for the three statuses. It isn't clear to me if this won't be too much information to pack into small dots on a map with a lot of different colors going on.  

 I mentioned that to aldo in #design and am waiting for a house icon version of the agua requerido icon.

**Comment by okdistribute** [comment]
Going to merge this and update the icons when we have them in a separate commit, since that's all that's left here.

**Pull request merged**
